# Generated by Django 3.0 on 2021-04-18 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210418_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='createdAt',
        ),
    ]
